name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  modal_progress_hud: ^0.1.3
  flutter_dropdown: ^1.0.0+hotfix.1
  rflutter_alert: ^2.0.4
  intl: ^0.17.0
  custom_switch: ^0.0.1
  syncfusion_flutter_charts: ^19.3.48
  finance: ^0.1.0
  mccounting_text: ^0.1.0
  clock: ^1.1.0
  percent_indicator: "^2.1.7+2"
  shared_preferences: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
